# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fef27b864aff658a834414b1f848963ed13efe80cd6fef597aca514f5b7f83ef464101c28e9d12339b6708b131c5784e39755f42206682eb478f24a67820e228

test:
  secret_key_base: ea26378ef9c5546be64b0581f9a68dc9a39c131034fbc298f8d910a329c8e1d7b5c57cabac4fe47af5f383025e33fb6f48d2a1c1d2ee93aba06faa3fa1611af8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
